services:
  spider:
    build: .
    container_name: open-webui-spider-rs
    security_opt:
      - seccomp:unconfined
    ports:
      - "8081:8081"
    environment:
      - RUST_LOG=info
      - APP_CHROME_CONNECTION_URL=http://headless-chrome:6000/json/version
      - APP_PORT=8081
      - no_proxy=headless-chrome,localhost,127.0.0.1
      - NO_PROXY=headless-chrome,localhost,127.0.0.1
    depends_on:
      - headless-chrome
    networks:
      - spider-rs-network

  headless-chrome:
    image: ghcr.io/llukas22/headless-browser-playwright:latest
    container_name: headless-chrome
    networks:
      - spider-rs-network
    environment:
      - REMOTE_ADDRESS=headless-chrome
      - HOSTNAME_OVERRIDE=headless-chrome
      - CHROME_ARGS=--remote-allow-origins=*
      - no_proxy=localhost,127.0.0.1
      - NO_PROXY=localhost,127.0.0.1

networks:
  spider-rs-network:
    name: spider-rs-network
